### ISSUE TITLE
Feat: 논의가 필요한 추가 기능 (TODO)

### ISSUE THREAD

**Issue by yunchaeney** [INtiful/SootheWithMe#117]
### 의논 필요 : 팀원들의 의견을 수용하여 결정이 필요한 부분
- [x] 모임의 `{name}` 값 처리 관련
- [x] ~~#118~~
- [x] ~~react-toast 적용~~
- [ ]  API 의 캐시 관련 처리
- [x] ~~API 요청 시 쿼리스트링 라이브러리 사용 여부 (ex. qs, query-string)~~
- [x] ~~공통된 Error 처리 : toast로 error 메세지 보내기~~
- [x] ~~모임 찾기 페이지에서는 마감여부  filtering 에 대한 의견~~

### TODO : 필수적으로 진행해야 하는 부분
- [ ] 페이지 컴포넌트 테스트 코드 작성

### 추가 개발 : 모든 개발이 완료되면, 우선순위를 결정하여 추가로 개발한다
- [x] 다크모드 적용
- [ ] 무한스크롤로 추가 fetch data에 스켈레톤 UI 적용

### Refactor TODO
- [x] ~~Filters, Chips 등 중복되는 컴포넌트를 확장성 있게 만들어 공통 컴포넌트로 사용하기~~
- [x] ~~FilterList, FilterSort, Card.bak 등 더이상 사용되지 않는 컴포넌트 삭제~~
- [x] ~~dallaemfit 오탈자 사용된 부분 고치기~~
- [x] ~~중복적으로 사용되는 type : 'DALLAEMFIT' | 'OFFICE_STRETCHING' | 'MINDFULNESS' | 'WORKATION' 등에 대해 type 폴더에 선언~~

**Comment by yunchaeney** [comment]
# 모임의 {name} 값 처리 관련

1. API 명세서에서는 빠졌으나, post 요청 시 name 값 전송이 가능한 걸로 알고 있습니다.
- 모임 만들기 모달에서 모임명을 추가로 입력 받음

2. 모임 type을 name으로 사용
- 피그마 디자인처럼, name 값에 한글로 "달램핏 오피스 스트레칭" , "워케이션" 등의 한글명을 사용함

정도의 방안이 생각납니다.

**Comment by BeMatthewsong** [comment]
모임 이름이 있는 게 모임마다 구분하는 데에 중요한 역할이라고 생각해서, 이름을 추가하는 방식에 1표 던집니다!

**Comment by BeMatthewsong** [comment]
![image](https://github.com/user-attachments/assets/0d4e6b43-d993-4884-bd9a-e363b5fdc90d)
